name: Build Unity Example

on: [workflow_dispatch]

jobs:
  build:
    name: Build Unity Example Project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Examples/OSCQueryExplorer-Unity/Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: StandaloneWindows64
          projectPath: Examples/OSCQueryExplorer-Unity
          buildName: OSCQueryExplorer-Unity
      
      # Version
      - name: Set Version from Tag
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          echo "GIT_TAG= $(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          
      - name: Compress
        shell: bash
        run: 7z a -tzip "OSCQueryExplorer-Unity-${{env.GIT_TAG}}.zip" "./build/StandaloneWindows64/*"
        
      # Publish
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "OSCQueryExplorer-Unity-${{env.GIT_TAG}}.zip"
          tag_name: ${{ env.GIT_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}